# -*- coding: utf-8 -*-
"""Path Planning [Datasets].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVxOYd5cVmMJqD2aVgksrFXwyUL__b8h
"""

# Install libraries
!pip install -q gpytorch tabulate tqdm easydict
!pip install gymnasium
!pip install tensorboard
!pip install --upgrade sympy

# Create project directories
!mkdir -p Environment/Maps
!mkdir -p Algorithm/DRL/Agent/SAC

# Environment Definition
import gymnasium as gym
from gymnasium import spaces
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Normal
from collections import deque
import random
import os
import csv
import matplotlib.pyplot as plt
from scipy.interpolate import NearestNDInterpolator # For evaluation map
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from torch.utils.tensorboard import SummaryWriter
from datetime import datetime
import argparse
import sys

class MultiAgentMonitoring(gym.Env):
    def __init__(self, map_size=(50, 41), num_agents=2, movement_cost_factor=0.01,
                 sensor_stds=0.05, reward_weights=None, max_episode_steps=1000,
                 map_data_path=None, reward_scale_factor=1.0,
                 collision_threshold=0.05, collision_penalty=-5.0, # Collision parameters
                 reward_visited_cells=1.0, reward_peak_discovery=5.0,
                 penalty_time=0.00001, penalty_revisit=0.0):
        super(MultiAgentMonitoring, self).__init__()

        self.map_size = map_size # (rows, columns)
        self.num_agents = num_agents
        self.movement_cost_factor = movement_cost_factor
        self.sensor_stds = sensor_stds
        self.max_episode_steps = max_episode_steps
        self.reward_scale_factor = reward_scale_factor

        # Collision parameters
        self.collision_threshold = collision_threshold
        self.collision_penalty = collision_penalty

        self.gt_map = self._load_map_from_csv(map_data_path)
        # Validate loaded map shape against specified map_size (rows, columns)
        if self.gt_map.shape != self.map_size:
            raise ValueError(f"Loaded map shape {self.gt_map.shape} does not match specified map_size {self.map_size}. Please check map_configs in run_training_and_evaluation.")

        self.gt_map_min = np.min(self.gt_map)
        self.gt_map_max = np.max(self.gt_map)
        self.gt_map_normalized = (self.gt_map - self.gt_map_min) / (self.gt_map_max - self.gt_map_min + 1e-6)

        # Track initial visited cells count for reward calculation per step
        self.initial_visited_cells_count = 0
        self.visited_map = np.zeros(self.map_size) # Reset visited map per episode

        # The 'reward_weights' dict argument is now deprecated in favor of individual args
        self.reward_weights = {
            'visited_cells': reward_visited_cells,
            'peak_discovery': reward_peak_discovery,
            'time_penalty': penalty_time,
            'revisit_penalty': penalty_revisit
        }

        # Action space: num_agents * 2 (for x, y delta for each agent)
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(self.num_agents, 2), dtype=np.float32)

        # Observation space: num_agents * (x_pos, y_pos, sensed_value)
        self.observation_dim = self.num_agents * 3
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(self.observation_dim,), dtype=np.float32)

        self.current_step = 0
        self.fleet_positions = None
        self.np_random = None # Will be set in reset

    def _load_map_from_csv(self, map_data_path):

        if map_data_path is None or not os.path.exists(map_data_path):
            raise ValueError(f"Map data path '{map_data_path}' is invalid or does not exist.")

        map_data = []
        try:
            with open(map_data_path, 'r') as f:
                reader = csv.reader(f)
                for row in reader:
                    # Filter out empty strings that can result from extra commas or malformed rows
                    cleaned_row = [x.strip() for x in row if x.strip()]
                    if not cleaned_row: # Skip empty rows
                        continue
                    map_data.append([float(x) for x in cleaned_row])
            print(f"\n SUCCESS: Loaded {map_data_path} with shape: ({len(map_data)}, {len(map_data[0])}) with ',' delimiter.")
        except (ValueError, IndexError): # IndexError if a row is empty after cleaning, ValueError if float conversion fails
            # If comma-separated fails, try space delimiter
            map_data = [] # Reset map_data
            try:
                with open(map_data_path, 'r') as f:
                    # Manually read line by line and split by space
                    for line in f:
                        # Split by space and filter out empty strings
                        cleaned_row = [x.strip() for x in line.split(' ') if x.strip()]
                        if not cleaned_row: # Skip empty lines
                            continue
                        map_data.append([float(x) for x in cleaned_row])
                print(f"\n SUCCESS: Loaded {map_data_path} with shape: ({len(map_data)}, {len(map_data[0])}) with ' ' delimiter.")
            except Exception as e:
                raise ValueError(f"Failed to load map from {map_data_path}. Tried comma and space delimiters. Error: {e}")

        loaded_map = np.array(map_data, dtype=np.float32)
        return loaded_map

    def _get_obs(self):
        obs = []
        for i in range(self.num_agents):
            x, y = self.fleet_positions[i]
            x_int, y_int = int(round(x)), int(round(y))
            x_int = np.clip(x_int, 0, self.map_size[1] - 1)
            y_int = np.clip(y_int, 0, self.map_size[0] - 1)

            true_value = self.gt_map_normalized[y_int, x_int]
            noisy_value = true_value + self.np_random.normal(0, self.sensor_stds)
            noisy_value = np.clip(noisy_value, 0.0, 1.0)

            # Normalize positions to [0, 1] range
            obs.extend([x / (self.map_size[1] -1), y / (self.map_size[0] -1), noisy_value])

        return np.array(obs, dtype=np.float32)

    def _sense_and_record(self):
        sensed_values_at_step = []
        for i in range(self.num_agents):
            x, y = self.fleet_positions[i]
            x_int, y_int = int(round(x)), int(round(y))
            x_int = np.clip(x_int, 0, self.map_size[1] - 1)
            y_int = np.clip(y_int, 0, self.map_size[0] - 1)

            true_value = self.gt_map_normalized[y_int, x_int]
            noisy_value = true_value + self.np_random.normal(0, self.sensor_stds)
            noisy_value = np.clip(noisy_value, 0.0, 1.0)

            sensed_values_at_step.append((x, y, noisy_value))
            # Only mark as visited if it's not an obstacle (value above threshold)
            if true_value >= self.collision_threshold:
                self.visited_map[y_int, x_int] = 1 # Mark cell as visited

        return sensed_values_at_step

    def _calculate_reward(self, current_sensed_values_info):
        reward = 0.0

        # Reward for visiting NEW cells
        current_visited_cells_count = np.sum(self.visited_map)
        newly_visited_cells = current_visited_cells_count - self.initial_visited_cells_count
        reward += self.reward_weights['visited_cells'] * newly_visited_cells
        self.initial_visited_cells_count = current_visited_cells_count # Update for next step's calculation

        # Reward for discovering high-value peaks at current step
        current_step_sensed_values = [val for _, _, val in current_sensed_values_info]
        if current_step_sensed_values:
            peak_reward = np.max(current_step_sensed_values)
            reward += self.reward_weights['peak_discovery'] * peak_reward

        # Penalty for each time step
        reward -= self.reward_weights['time_penalty']

        return reward * self.reward_scale_factor

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        if seed is not None:
            self.np_random, _ = gym.utils.seeding.np_random(seed)
        else:
            self.np_random, _ = gym.utils.seeding.np_random()

        self.fleet_positions = np.zeros((self.num_agents, 2), dtype=np.float32)

        # Initialize agents in valid (non-obstacle) positions
        for i in range(self.num_agents):
            valid_pos_found = False
            attempts = 0
            while not valid_pos_found and attempts < 1000: # Limit attempts
                x = self.np_random.uniform(0, self.map_size[1]) # x-coordinate
                y = self.np_random.uniform(0, self.map_size[0]) # y-coordinate
                x_int, y_int = int(round(x)), int(round(y))

                # Check if the proposed starting position is traversable
                if 0 <= y_int < self.map_size[0] and 0 <= x_int < self.map_size[1]:
                    if self.gt_map_normalized[y_int, x_int] >= self.collision_threshold:
                        self.fleet_positions[i, 0] = x
                        self.fleet_positions[i, 1] = y
                        valid_pos_found = True
                    else:
                        attempts += 1
                else:
                    attempts += 1

            if not valid_pos_found:
                print(f"Warning: Could not find a valid starting position for agent {i}. Placing at (0,0).")
                self.fleet_positions[i, 0] = 0
                self.fleet_positions[i, 1] = 0


        self.current_step = 0
        self.visited_map = np.zeros(self.map_size) # Reset visited map for the new episode
        self.initial_visited_cells_count = 0 # Reset for new episode reward calculation

        initial_sensed_values = self._sense_and_record()
        self.initial_visited_cells_count = np.sum(self.visited_map) # Set initial count after first sensing

        obs = self._get_obs()
        info = {"fleet_positions": self.fleet_positions.copy(), "sensed_values": initial_sensed_values}

        self.terminated = False
        self.truncated = False

        return obs, info

    def step(self, action):
        # Action is expected to be flattened from the agent, reshape it back to (num_agents, 2)
        action = np.array(action).reshape(self.num_agents, 2)

        # Store old positions to revert in case of collision
        old_positions = self.fleet_positions.copy()
        current_reward = 0.0 # Start with base reward calculation

        # Calculate intended new positions
        intended_new_positions = self.fleet_positions + action

        # Process each agent's movement
        new_fleet_positions = old_positions.copy() # Start with old positions
        for i in range(self.num_agents):
            int_x = int(round(intended_new_positions[i, 0]))
            int_y = int(round(intended_new_positions[i, 1]))

            # Check if intended position is within map bounds
            if 0 <= int_x < self.map_size[1] and 0 <= int_y < self.map_size[0]:
                # Check for collision with map obstacles
                if self.gt_map_normalized[int_y, int_x] < self.collision_threshold:
                    # Collision detected: stay at old position and apply penalty
                    new_fleet_positions[i] = old_positions[i]
                    current_reward += self.collision_penalty
                    # print(f"Agent {i} collided with obstacle at ({int_x}, {int_y}). Penalty: {self.collision_penalty}") # For debugging
                else:
                    # No collision, update position
                    new_fleet_positions[i] = intended_new_positions[i]
            else:
                # Out of bounds: clip and apply penalty
                new_fleet_positions[i, 0] = np.clip(intended_new_positions[i, 0], 0, self.map_size[1] - 1)
                new_fleet_positions[i, 1] = np.clip(intended_new_positions[i, 1], 0, self.map_size[0] - 1)
                current_reward += self.collision_penalty # Apply penalty for hitting boundaries
                # print(f"Agent {i} went out of bounds. Penalty: {self.collision_penalty}") # For debugging

        self.fleet_positions = new_fleet_positions # Update actual positions

        # Calculate movement cost based on the attempted action magnitude
        movement_cost = np.sum(np.abs(action)) * self.movement_cost_factor

        # Sense values at new positions and record visited cells
        current_sensed_values_info = self._sense_and_record()

        # Calculate base reward from environment features (visited cells, peak discovery, time penalty)
        reward_from_env = self._calculate_reward(current_sensed_values_info)

        # Apply reward_scale_factor to the sum of all components
        reward = (reward_from_env - movement_cost + current_reward) * self.reward_scale_factor

        self.current_step += 1

        terminated = False
        truncated = self.current_step >= self.max_episode_steps # Episode ends if max steps reached

        obs = self._get_obs()
        info = {"fleet_positions": self.fleet_positions.copy(), "sensed_values": current_sensed_values_info}

        return obs, reward, terminated, truncated, info

    def render(self):
        plt.figure(figsize=(10, 8))

        plt.imshow(self.gt_map_normalized, origin='lower', cmap='viridis', alpha=0.7)

        obstacle_mask = self.gt_map_normalized < self.collision_threshold
        plt.imshow(obstacle_mask, origin='lower', cmap='binary', alpha=0.5) # Black/white for obstacles

        # Plot visited cells
        visited_mask = self.visited_map > 0
        plt.imshow(visited_mask, origin='lower', cmap='bone_r', alpha=0.3)

        if self.fleet_positions is not None:
            plt.scatter(self.fleet_positions[:, 0], self.fleet_positions[:, 1],
                        c='red', marker='o', s=100, label='Agents', edgecolors='black')

        plt.title(f"Map Monitoring - Step: {self.current_step}")
        plt.xlabel("X Coordinate")
        plt.ylabel("Y Coordinate")
        plt.colorbar(label="Normalized Value")
        plt.legend()
        plt.grid(True)
        plt.show()

    def close(self):
        plt.close()

# Replay Buffer
class ReplayBuffer:
    def __init__(self, capacity):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size):
        if len(self.buffer) < batch_size:
            raise ValueError(f"Replay buffer has {len(self.buffer)} samples, but batch_size is {batch_size}. Not enough samples.")

        state, action, reward, next_state, done = zip(*random.sample(self.buffer, batch_size))

        return np.array(state, dtype=np.float32), \
               np.array(action, dtype=np.float32), \
               np.array(reward, dtype=np.float32), \
               np.array(next_state, dtype=np.float32), \
               np.array(done, dtype=np.float32)

    def __len__(self):
        return len(self.buffer)

# Networks for SAC
class ValueNetwork(nn.Module):
    def __init__(self, observation_dim, hidden_size):
        super(ValueNetwork, self).__init__()
        self.fc1 = nn.Linear(observation_dim, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, 1) # Output a single value

    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

class QNetwork(nn.Module):
    def __init__(self, observation_dim, action_dim, hidden_size):
        super(QNetwork, self).__init__()
        # Q1 architecture
        self.fc1_q1 = nn.Linear(observation_dim + action_dim, hidden_size)
        self.fc2_q1 = nn.Linear(hidden_size, hidden_size)
        self.fc3_q1 = nn.Linear(hidden_size, 1) # Output a single Q-value

        # Q2 architecture
        self.fc1_q2 = nn.Linear(observation_dim + action_dim, hidden_size)
        self.fc2_q2 = nn.Linear(hidden_size, hidden_size)
        self.fc3_q2 = nn.Linear(hidden_size, 1) # Output a single Q-value

    def forward(self, state, action):
        sa = torch.cat([state, action], dim=1) # Concatenate state and action

        x1 = F.relu(self.fc1_q1(sa))
        x1 = F.relu(self.fc2_q1(x1))
        q1 = self.fc3_q1(x1)

        x2 = F.relu(self.fc1_q2(sa))
        x2 = F.relu(self.fc2_q2(x2))
        q2 = self.fc3_q2(x2)
        return q1, q2 # Returns two separate tensors

class GaussianPolicy(nn.Module):
    def __init__(self, observation_dim, action_dim, hidden_size):
        super(GaussianPolicy, self).__init__()
        self.fc1 = nn.Linear(observation_dim, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.mean_linear = nn.Linear(hidden_size, action_dim)
        self.log_std_linear = nn.Linear(hidden_size, action_dim)

        self.log_std_min = -20
        self.log_std_max = 2

    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        mean = self.mean_linear(x)
        log_std = self.log_std_linear(x)
        log_std = torch.clamp(log_std, self.log_std_min, self.log_std_max)
        return mean, log_std

    def sample(self, state):
        mean, log_std = self.forward(state)
        std = log_std.exp()
        normal = Normal(mean, std)
        z = normal.sample()
        action = torch.tanh(z) # Squashed Gaussian

        log_prob = normal.log_prob(z)
        log_prob = log_prob.sum(1, keepdim=True) # Sum over action dimensions

        # Apply transformation to log_prob for squashing
        log_prob -= torch.log(1 - action.pow(2) + 1e-6).sum(1, keepdim=True)
        return action, log_prob, mean, log_std

    def to(self, device):
        self.device = device
        return super(GaussianPolicy, self).to(device)

# SAC Agent Definition
class SACAgent:
    def __init__(self, observation_dim, action_dim, args, writer):
        self.gamma = args.gamma
        self.tau = args.tau
        self.lr = args.lr
        # Initialize alpha as a tensor on the correct device
        self.alpha = torch.tensor(args.alpha, requires_grad=False, device=args.device)
        self.auto_entropy_tuning = args.auto_entropy_tuning
        self.target_entropy = -torch.prod(torch.Tensor([action_dim]).to(args.device)).item()
        self.hidden_size = args.hidden_size
        self.device = args.device
        self.writer = writer # TensorBoard writer

        # Value Network
        self.value_net = ValueNetwork(observation_dim, self.hidden_size).to(self.device)
        self.target_value_net = ValueNetwork(observation_dim, self.hidden_size).to(self.device)

        # Q Networks
        self.q_net1 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)
        self.q_net2 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)

        self.target_q_net1 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)
        self.target_q_net2 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)

        # Policy Network
        self.policy_net = GaussianPolicy(observation_dim, action_dim, self.hidden_size).to(self.device)

        # Copy initial weights to target networks
        for target_param, param in zip(self.target_value_net.parameters(), self.value_net.parameters()):
            target_param.data.copy_(param.data)
        for target_param, param in zip(self.target_q_net1.parameters(), self.q_net1.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)
        for target_param, param in zip(self.target_q_net2.parameters(), self.q_net2.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)


        # Optimizers
        self.value_optimizer = optim.Adam(self.value_net.parameters(), lr=self.lr)
        self.q1_optimizer = optim.Adam(self.q_net1.parameters(), lr=self.lr)
        self.q2_optimizer = optim.Adam(self.q_net2.parameters(), lr=self.lr)
        self.policy_optimizer = optim.Adam(self.policy_net.parameters(), lr=self.lr)

        # Entropy tuning (alpha)
        if self.auto_entropy_tuning:
            # Ensure log_alpha is initialized from the tensor alpha
            self.log_alpha = torch.tensor(np.log(self.alpha.item()), requires_grad=True, device=self.device)
            self.alpha_optimizer = optim.Adam([self.log_alpha], lr=self.lr)
        else:
             pass

        self.replay_buffer = ReplayBuffer(args.replay_size)
        self.batch_size = args.batch_size
        self.updates = 0 # Counter for optimization steps

    def select_action(self, state, evaluate=False):
        # Convert numpy state to torch tensor, add batch dimension
        state = torch.FloatTensor(state).to(self.device).unsqueeze(0)

        if evaluate is False:
            # Sample action from the policy distribution for exploration/training
            action, log_prob, _, _ = self.policy_net.sample(state)
        else:
            # Use deterministic action (mean) for evaluation
            action_mean, _ = self.policy_net.forward(state)
            action = torch.tanh(action_mean)

        # Convert back to numpy array and remove batch dimension
        return action.detach().cpu().numpy()[0]

    def update_parameters(self, memory, batch_size, updates, writer):
        # Sample a batch from replay buffer
        try:
            state_batch, action_batch, reward_batch, next_state_batch, terminated_batch = memory.sample(batch_size)
        except ValueError as e:
            print(f"Warning: Not enough samples in replay buffer for batch size {batch_size}. Skipping update.")
            return

        # Convert numpy arrays to torch tensors
        state_batch = torch.FloatTensor(state_batch).to(self.device)
        action_batch = torch.FloatTensor(action_batch).to(self.device)
        reward_batch = torch.FloatTensor(reward_batch).unsqueeze(1).to(self.device) # Ensure (batch_size, 1)
        next_state_batch = torch.FloatTensor(next_state_batch).to(self.device)
        terminated_batch = torch.FloatTensor(terminated_batch).unsqueeze(1).to(self.device) # Ensure (batch_size, 1)

        # Calculate V_target for Value Network Update
        with torch.no_grad():
            # Sample next action from current policy for V-target calculation
            next_action, log_prob, _, _ = self.policy_net.sample(next_state_batch)

            # Extract tensor outputs from Q-networks before using torch.min
            q1_next_target, _ = self.target_q_net1(next_state_batch, next_action)
            q2_next_target, _ = self.target_q_net2(next_state_batch, next_action)

            min_q_next_target = torch.min(q1_next_target, q2_next_target) - self.alpha * log_prob

            # Bellman backup for the value network
            next_value = reward_batch + (1 - terminated_batch) * self.gamma * min_q_next_target

        # Value Network Update
        value_pred = self.value_net(state_batch)
        value_loss = F.mse_loss(value_pred, next_value)

        self.value_optimizer.zero_grad()
        value_loss.backward()
        nn.utils.clip_grad_norm_(self.value_net.parameters(), max_norm=1.0)
        self.value_optimizer.step()

        # Q Network Update
        q1_pred, _ = self.q_net1(state_batch, action_batch)
        q2_pred, _ = self.q_net2(state_batch, action_batch)

        # Use target_value_net for Q-target calculation
        with torch.no_grad():
            q_target = reward_batch + (1 - terminated_batch) * self.gamma * self.target_value_net(next_state_batch)

        q1_loss = F.mse_loss(q1_pred, q_target.detach())
        q2_loss = F.mse_loss(q2_pred, q_target.detach())

        self.q1_optimizer.zero_grad()
        q1_loss.backward()
        nn.utils.clip_grad_norm_(self.q_net1.parameters(), max_norm=1.0)
        self.q1_optimizer.step()

        self.q2_optimizer.zero_grad()
        q2_loss.backward()
        nn.utils.clip_grad_norm_(self.q_net2.parameters(), max_norm=1.0)
        self.q2_optimizer.step()

        # Policy Network Update
        new_action, log_prob, _, _ = self.policy_net.sample(state_batch)

        # Extract tensor outputs from Q-networks before using torch.min
        q1_new_action, _ = self.q_net1(state_batch, new_action)
        q2_new_action, _ = self.q_net2(state_batch, new_action)
        min_q_new_action = torch.min(q1_new_action, q2_new_action)

        # Policy loss: maximize (Q-value + entropy bonus)
        policy_loss = (self.alpha * log_prob - min_q_new_action).mean() # Uses self.alpha (tensor)

        self.policy_optimizer.zero_grad()
        policy_loss.backward()
        nn.utils.clip_grad_norm_(self.policy_net.parameters(), max_norm=1.0)
        self.policy_optimizer.step()

        # Alpha (Entropy)
        alpha_loss = torch.tensor(0.).to(self.device) # Default alpha loss is 0
        if self.auto_entropy_tuning:
            alpha_loss = -(self.log_alpha * (log_prob.detach() + self.target_entropy)).mean()

            self.alpha_optimizer.zero_grad()
            alpha_loss.backward()
            self.alpha_optimizer.step()
            self.alpha = self.log_alpha.exp()

        # Soft update of target networks
        for target_param, param in zip(self.target_value_net.parameters(), self.value_net.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)
        for target_param, param in zip(self.target_q_net1.parameters(), self.q_net1.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)
        for target_param, param in zip(self.target_q_net2.parameters(), self.q_net2.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)

        # Log metrics to TensorBoard
        if writer is not None:
            writer.add_scalar('loss/value_loss', value_loss.item(), updates)
            writer.add_scalar('loss/q1_loss', q1_loss.item(), updates)
            writer.add_scalar('loss/q2_loss', q2_loss.item(), updates)
            writer.add_scalar('loss/policy_loss', policy_loss.item(), updates)
            # Ensure alpha is a tensor before calling .item()
            writer.add_scalar('alpha', self.alpha.item(), updates)
            writer.add_scalar('loss/alpha_loss', alpha_loss.item(), updates)
            writer.add_scalar('q_values/q1_mean', q1_pred.mean().item(), updates)
            writer.add_scalar('q_values/q2_mean', q2_pred.mean().item(), updates)
            writer.add_scalar('q_values/q_target_mean', q_target.mean().item(), updates)
            writer.add_scalar('value_net/value_mean', value_pred.mean().item(), updates)

# Evaluation Function
import numpy as np
from scipy.interpolate import LinearNDInterpolator
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import os
import matplotlib.pyplot as plt

def evaluate_agent(env, agent, num_episodes, seed, log_dir, run_name):
    print("\n Starting Evaluation ")

    all_episode_rewards = []
    all_mae_visited_cells = []
    all_mses_full_map = []
    all_r2s_full_map = []
    all_cmses = []

    all_sensed_data_coords = []
    all_sensed_data_values = []

    for i_episode in range(num_episodes):
        obs, info = env.reset(seed=seed + i_episode)
        done = False
        truncated = False
        episode_reward = 0
        episode_sensed_coords = [] # Sensed coords for current episode
        episode_sensed_values = [] # Sensed values for current episode

        episode_visited_cells = np.zeros(env.env.map_size)

        # Record initial sensed values and mark initial positions as visited
        for x_init, y_init, sensed_val_init in info["sensed_values"]:
            episode_sensed_coords.append((x_init, y_init))
            episode_sensed_values.append(sensed_val_init)
            x_int, y_int = int(round(x_init)), int(round(y_init))
            if 0 <= y_int < env.env.map_size[0] and 0 <= x_int < env.env.map_size[1]:
                if env.env.gt_map_normalized[y_int, x_int] >= env.env.collision_threshold:
                    episode_visited_cells[y_int, x_int] = 1

        print(f"Environment reset. Initial positions: {info['fleet_positions'].tolist()}") #

        while not done and not truncated:
            action = agent.select_action(obs, evaluate=True)
            action_reshaped_for_env = action.reshape(env.env.num_agents, 2)
            obs, reward, done, truncated, info = env.step(action_reshaped_for_env)
            episode_reward += reward

            # Update visited cells for this episode
            for pos_x, pos_y in info["fleet_positions"]:
                x_int, y_int = int(round(pos_x)), int(round(pos_y))
                # Ensure coordinates are within map bounds before marking visited
                if 0 <= y_int < env.env.map_size[0] and 0 <= x_int < env.env.map_size[1]:
                    # Only mark as visited if it's not an obstacle during evaluation
                    if env.env.gt_map_normalized[y_int, x_int] >= env.env.collision_threshold:
                        episode_visited_cells[y_int, x_int] = 1

            # Record sensed values at current step
            for x_curr, y_curr, sensed_val_curr in info["sensed_values"]:
                episode_sensed_coords.append((x_curr, y_curr))
                episode_sensed_values.append(sensed_val_curr)

        all_episode_rewards.append(episode_reward)

        # Prepare data for metrics on visited cells and full map interpolation
        unique_episode_sensed_data = {}
        for (x, y), val in zip(episode_sensed_coords, episode_sensed_values):
            unique_episode_sensed_data[(round(x), round(y))] = val

        sensed_coords_unique = np.array(list(unique_episode_sensed_data.keys()))
        sensed_values_unique = np.array(list(unique_episode_sensed_data.values()))

        # If there's any sensed data in this episode
        if sensed_coords_unique.shape[0] > 0:
            # Filter ground truth to only include traversable cells that were visited
            gt_visited_cells_indices = np.where((episode_visited_cells == 1) & (env.env.gt_map_normalized >= env.env.collision_threshold))
            gt_visited_cells_values = env.env.gt_map_normalized[gt_visited_cells_indices]

            # Filter sensed_coords and values to only include points that correspond to actually visited, traversable cells
            filtered_sensed_coords_for_mae = []
            filtered_sensed_values_for_mae = []
            for (sx, sy), sval in unique_episode_sensed_data.items():
                x_int, y_int = int(round(sx)), int(round(sy))
                if (0 <= y_int < env.env.map_size[0] and 0 <= x_int < env.env.map_size[1] and
                    episode_visited_cells[y_int, x_int] == 1 and env.env.gt_map_normalized[y_int, x_int] >= env.env.collision_threshold):
                    filtered_sensed_coords_for_mae.append((sx, sy))
                    filtered_sensed_values_for_mae.append(sval)

            filtered_sensed_coords_for_mae = np.array(filtered_sensed_coords_for_mae)
            filtered_sensed_values_for_mae = np.array(filtered_sensed_values_for_mae)

            # Check for sufficient unique sensed points for interpolation specifically for visited cells MAE
            if filtered_sensed_coords_for_mae.shape[0] >= 3 and len(gt_visited_cells_values) > 0:
                 # Check if points are collinear (simple check: if all points lie on a line)
                 # This is a basic check; a more robust check might involve SVD or PCA
                 if filtered_sensed_coords_for_mae.shape[0] > 3:
                     diffs = np.diff(filtered_sensed_coords_for_mae, axis=0)
                     # Check if ratios of differences are constant (within a tolerance)
                     if np.all(np.isclose(diffs[1:, 0] * diffs[0, 1], diffs[1:, 1] * diffs[0, 0])):
                         print(f"Warning: Sensed points for MAE on visited cells appear collinear in episode {i_episode}. Skipping MAE calculation.")
                         all_mae_visited_cells.append(np.nan)
                     else:
                         # Create grid points specifically for the visited, traversable cells
                         visited_grid_points = np.column_stack((gt_visited_cells_indices[1], gt_visited_cells_indices[0])) # (x, y)
                         interp_func_mae = LinearNDInterpolator(filtered_sensed_coords_for_mae, filtered_sensed_values_for_mae)
                         interpolated_visited_values = interp_func_mae(visited_grid_points[:,0], visited_grid_points[:,1])
                         # Handle potential NaNs from interpolation outside convex hull
                         valid_interp_mask = ~np.isnan(interpolated_visited_values)
                         if np.sum(valid_interp_mask) > 0:
                             mae_visited_cells = mean_absolute_error(gt_visited_cells_values[valid_interp_mask], interpolated_visited_values[valid_interp_mask])
                             all_mae_visited_cells.append(mae_visited_cells)
                         else:
                             print(f"Warning: Linear interpolation for MAE on visited cells resulted in all NaNs in episode {i_episode}. Setting MAE to NaN.")
                             all_mae_visited_cells.append(np.nan)
                 else:
                     # Less than 3 points, cannot perform LinearND interpolation
                     print(f"Warning: Not enough unique sensed points ({filtered_sensed_coords_for_mae.shape[0]}) for LinearND interpolation for MAE calculation on visited, traversable cells in episode {i_episode}. Setting MAE to NaN.")
                     all_mae_visited_cells.append(np.nan)
            else:
                # Not enough points or no visited traversable cells
                all_mae_visited_cells.append(np.nan)


            traversable_indices = np.where(env.env.gt_map_normalized >= env.env.collision_threshold)
            traversable_grid_points = np.column_stack((traversable_indices[1], traversable_indices[0])) # (x,y)

            # Use all unique sensed data for full map interpolation
            if sensed_coords_unique.shape[0] >= 3:
                # Check if all overall unique sensed points are collinear for full map interpolation
                if sensed_coords_unique.shape[0] > 2:
                    diffs_overall = np.diff(sensed_coords_unique, axis=0)
                    if np.all(np.isclose(diffs_overall[1:, 0] * diffs_overall[0, 1], diffs_overall[1:, 1] * diffs_overall[0, 0])):
                         print(f"Warning: Overall sensed points for full map interpolation appear collinear in episode {i_episode}. Skipping full map metrics.")
                         all_mses_full_map.append(np.nan)
                         all_r2s_full_map.append(np.nan)
                         all_cmses.append(np.nan)
                    else:
                        interp_func_full = LinearNDInterpolator(sensed_coords_unique, sensed_values_unique)

                        # Interpolate only for traversable grid points
                        interpolated_values_at_traversable_points = interp_func_full(traversable_grid_points[:,0], traversable_grid_points[:,1])

                        interpolated_full_map_values = np.full(env.env.map_size, np.nan) # Initialize with NaN
                        interpolated_full_map_values[traversable_indices] = interpolated_values_at_traversable_points

                        gt_map_flat_traversable = env.env.gt_map_normalized[traversable_indices]

                        interpolated_flat_traversable = interpolated_full_map_values[traversable_indices]

                        valid_metrics_mask = ~np.isnan(interpolated_flat_traversable)
                        if np.sum(valid_metrics_mask) > 0:
                            mse_full_map = mean_squared_error(gt_map_flat_traversable[valid_metrics_mask], interpolated_flat_traversable[valid_metrics_mask])
                            r2_full_map = r2_score(gt_map_flat_traversable[valid_metrics_mask], interpolated_flat_traversable[valid_metrics_mask])

                            # Cumulative MSE (CMSE) calculation (only on traversable areas with valid interpolation)
                            sorted_indices = np.argsort(gt_map_flat_traversable[valid_metrics_mask])
                            sorted_gt = gt_map_flat_traversable[valid_metrics_mask][sorted_indices]
                            sorted_interp = interpolated_flat_traversable[valid_metrics_mask][sorted_indices]

                            cumulative_mse = np.cumsum((sorted_gt - sorted_interp)**2) / (np.arange(len(sorted_gt)) + 1e-6)
                            cmse_x = cumulative_mse[-1] # CMSE(X) is the last value

                            all_mses_full_map.append(mse_full_map)
                            all_r2s_full_map.append(r2_full_map)
                            all_cmses.append(cmse_x)
                        else:
                            print(f"Warning: Linear interpolation for full map resulted in all NaNs in episode {i_episode}. Setting metrics to NaN.")
                            all_mses_full_map.append(np.nan)
                            all_r2s_full_map.append(np.nan)
                            all_cmses.append(np.nan)
                else:
                    # Less than 3 points, cannot perform LinearND interpolation
                    print(f"Warning: Not enough unique sensed points ({sensed_coords_unique.shape[0]}) for LinearND interpolation for full map in episode {i_episode}. Setting metrics to NaN.") #
                    all_mses_full_map.append(np.nan)
                    all_r2s_full_map.append(np.nan)
                    all_cmses.append(np.nan)

                all_sensed_data_coords.extend(sensed_coords_unique.tolist()) # Add unique sensed data to overall list
                all_sensed_data_values.extend(sensed_values_unique.tolist())

            else:
                print(f"Warning: Not enough unique sensed points ({sensed_coords_unique.shape[0]}) for LinearND interpolation for full map in episode {i_episode}. Setting metrics to NaN.") #
                all_mses_full_map.append(np.nan)
                all_r2s_full_map.append(np.nan)
                all_cmses.append(np.nan)

        else:
            print(f"Warning: No sensed values recorded in episode {i_episode}. Setting metrics to NaN.") #
            all_mae_visited_cells.append(np.nan)
            all_mses_full_map.append(np.nan)
            all_r2s_full_map.append(np.nan)
            all_cmses.append(np.nan)

    print("\n Evaluation complete.")

    # Calculate means, handling NaNs
    avg_reward = np.nanmean(all_episode_rewards) # Use nanmean to handle potential NaNs

    avg_mae_visited_cells = np.nanmean(all_mae_visited_cells)
    std_mae_visited_cells = np.nanstd(all_mae_visited_cells)
    # Calculate CI only if there are valid (non-NaN) MAE values
    valid_mae_count = np.sum(~np.isnan(all_mae_visited_cells))
    ci_mae_visited_cells = 1.96 * std_mae_visited_cells / np.sqrt(valid_mae_count) if valid_mae_count > 1 else np.nan


    avg_mse_full_map = np.nanmean(all_mses_full_map)
    std_mse_full_map = np.nanstd(all_mses_full_map)
    # Calculate CI only if there are valid (non-NaN) MSE values
    valid_mse_count = np.sum(~np.isnan(all_mses_full_map))
    ci_mse_full_map = 1.96 * std_mse_full_map / np.sqrt(valid_mse_count) if valid_mse_count > 1 else np.nan


    avg_r2_full_map = np.nanmean(all_r2s_full_map)
    std_r2_full_map = np.nanstd(all_r2s_full_map)
    # Calculate CI only if there are valid (non-NaN) R2 values
    valid_r2_count = np.sum(~np.isnan(all_r2s_full_map))
    ci_r2_full_map = 1.96 * std_r2_full_map / np.sqrt(valid_r2_count) if valid_r2_count > 1 else np.nan


    avg_cmse = np.nanmean(all_cmses)
    std_cmse = np.nanstd(all_cmses)
    # Calculate CI only if there are valid (non-NaN) CMSE values
    valid_cmse_count = np.sum(~np.isnan(all_cmses))
    ci_cmse = 1.96 * std_cmse / np.sqrt(valid_cmse_count) if valid_cmse_count > 1 else np.nan


    print(f"\n Final Evaluation Results for this Run:") #
    print(f"Avg. Reward: {avg_reward:.4f}") #
    print(f"Avg. MAE (Visited Cells): {avg_mae_visited_cells:.4f} (CI 95%: {ci_mae_visited_cells:.4f})")
    print(f"MSE (Full Map - Interpolated): {avg_mse_full_map:.4f} (CI 95%: {ci_mse_full_map:.4f})")
    print(f"R^2 (Full Map - Interpolated): {avg_r2_full_map:.4f} (CI 95%: {ci_r2_full_map:.4f})")
    print(f"CMSE(X): {avg_cmse:.4f} (CI 95%: {ci_cmse:.4f})")

    if all_sensed_data_coords:
        unique_overall_sensed_data = {}
        for (x, y), val in zip(all_sensed_data_coords, all_sensed_data_values):
            unique_overall_sensed_data[(round(x), round(y))] = val

        overall_sensed_coords = np.array(list(unique_overall_sensed_data.keys()))
        overall_sensed_values = np.array(list(unique_overall_sensed_data.values()))

        # Check for sufficient unique sensed points for overall map visualization
        if overall_sensed_coords.shape[0] >= 3:
            # Check if all overall unique sensed points are collinear for visualization
            if overall_sensed_coords.shape[0] > 2:
                 diffs_overall_plot = np.diff(overall_sensed_coords, axis=0)
                 if np.all(np.isclose(diffs_overall_plot[1:, 0] * diffs_overall_plot[0, 1], diffs_overall_plot[1:, 1] * diffs_overall_plot[0, 0])):
                     print("Warning: Overall sensed points for map visualization appear collinear. Plot not generated.")
                 else:
                     grid_x, grid_y = np.meshgrid(np.arange(env.env.map_size[1]), np.arange(env.env.map_size[0]))
                     grid_points = np.column_stack((grid_x.ravel(), grid_y.ravel()))

                     interp_func_overall = LinearNDInterpolator(overall_sensed_coords, overall_sensed_values)
                     overall_interpolated_map = interp_func_overall(grid_points[:,0], grid_points[:,1]).reshape(env.env.map_size)

                     fig, axes = plt.subplots(1, 2, figsize=(15, 7))

                     im1 = axes[0].imshow(env.env.gt_map_normalized, origin='lower', cmap='viridis')
                     axes[0].set_title('True Ground Truth Map (Normalized)')
                     axes[0].set_xlabel('X')
                     axes[0].set_ylabel('Y')
                     fig.colorbar(im1, ax=axes[0])

                     obstacle_mask_true = env.env.gt_map_normalized < env.env.collision_threshold
                     axes[0].imshow(obstacle_mask_true, origin='lower', cmap='binary', alpha=0.5)

                     im2 = axes[1].imshow(overall_interpolated_map, origin='lower', cmap='viridis',
                                          vmin=np.nanmin(env.env.gt_map_normalized), vmax=np.nanmax(env.env.gt_map_normalized)) # Use nanmin/nanmax
                     axes[1].set_title('Estimated Map (LinearND Interpolated)')
                     axes[1].set_xlabel('X')
                     axes[1].set_ylabel('Y')

                     # Add scatter plot of sensed points
                     axes[1].scatter(overall_sensed_coords[:,0], overall_sensed_coords[:,1],
                                     c='red', s=10, label='Sensed Points', alpha=0.7)
                     axes[1].legend()

                     fig.colorbar(im2, ax=axes[1])
                     plt.tight_layout()

                     plot_dir = os.path.join(log_dir, "evaluation_plots")
                     os.makedirs(plot_dir, exist_ok=True)
                     plot_path = os.path.join(plot_dir, f"{run_name}_Maps_LinearND.png") # Updated filename
                     plt.savefig(plot_path)
                     plt.close(fig)
                     print(f"Saved map visualization to {plot_path}")
            else:
                print("Warning: Not enough overall unique sensed points for final map visualization using LinearND interpolation. Plot not generated.")
        else:
            print("Warning: No overall unique sensed points recorded for final map visualization. Plot not generated.")

    metrics = {
        "Avg. Reward": avg_reward,
        "Avg. MAE (Visited Cells)": avg_mae_visited_cells,
        "MSE (Full Map - Interpolated)": avg_mse_full_map,
        "R^2 (Full Map - Interpolated)": avg_r2_full_map,
        "CMSE(X)": avg_cmse
    }
    return metrics

!pip install -q optuna

# Training and Evaluation Loop with Optuna Tuning
import json
import optuna
import warnings
import argparse
import torch
import os
import numpy as np
from datetime import datetime
from torch.utils.tensorboard import SummaryWriter
import random
import gymnasium as gym

class StateNormalizer(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)
        self.state_sum = np.zeros(self.observation_space.shape)
        self.state_sq_sum = np.zeros(self.observation_space.shape)
        self.state_count = 0
        self.state_mean = np.zeros(self.observation_space.shape)
        self.state_std = np.ones(self.observation_space.shape)
        self.epsilon = 1e-8
        self.is_training = True

    def _update_stats(self, obs):
        if not self.is_training:
            return
        self.state_sum += obs
        self.state_sq_sum += obs ** 2
        self.state_count += 1
        self.state_mean = self.state_sum / self.state_count
        self.state_std = np.sqrt(np.maximum(self.state_sq_sum / self.state_count - self.state_mean ** 2, self.epsilon))

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        self._update_stats(obs)
        normalized_obs = (obs - self.state_mean) / self.state_std
        return normalized_obs, info

    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)
        self._update_stats(obs)
        normalized_obs = (obs - self.state_mean) / self.state_std
        return normalized_obs, reward, terminated, truncated, info

    def set_training_mode(self, mode):
        self.is_training = mode

    def get_stats(self):
        return self.state_mean, self.state_std

def set_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def run_training_and_evaluation(args, map_configs):
    from __main__ import SACAgent, MultiAgentMonitoring, evaluate_agent

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    log_base_dir_overall = os.path.join("runs_tuning", f"MultiAgentMonitoring_Tune_Overall_{timestamp}")
    os.makedirs(log_base_dir_overall, exist_ok=True)

    results_summary_overall = {}

    # Iterate through all map configurations
    for map_comb_name, map_config in map_configs.items():
        map_data_path = map_config["map_data_path"]
        if not os.path.exists(map_data_path):
            print(f"Warning: Map file not found for {map_comb_name}: {map_data_path}. Skipping tuning for this map.")
            continue

        print(f"\n Starting Optuna Hyperparameter Optimization for Map: {map_comb_name} ")

        # Create a specific log directory for this map's tuning runs
        log_map_dir = os.path.join(log_base_dir_overall, map_comb_name)
        os.makedirs(log_map_dir, exist_ok=True)

        all_trials_results_map = []

        # Define the Optuna objective function for the current map
        def objective(trial):
            # Create a mutable copy of args for this trial's hyperparameters
            trial_args = type('Args', (object,), args.__dict__.copy())

            #Hyperparameters to be optimized by Optuna
            trial_args.lr = trial.suggest_float('lr', 1e-5, 1e-3, log=True) # SAC learning rate
            trial_args.batch_size = trial.suggest_categorical('batch_size', [64, 128, 256, 512])
            trial_args.gamma = trial.suggest_float('gamma', 0.95, 0.999) # Discount factor for SAC

            # Environment specific reward/penalty factors
            trial_args.reward_visited_cells = trial.suggest_float('reward_visited_cells', 0.1, 5.0)
            trial_args.reward_peak_discovery = trial.suggest_float('reward_peak_discovery', 1.0, 20.0)
            trial_args.penalty_time = trial.suggest_float('penalty_time', -0.1, -0.0001)
            trial_args.collision_penalty = trial.suggest_float('collision_penalty', -20.0, -1.0)

            # End Hyperparameter Suggestions
            current_run_seed = trial_args.seed + trial.number
            set_seed(current_run_seed)
            run_name = f"Trial{trial.number}_{datetime.now().strftime('%H-%M-%S')}"
            run_log_dir = os.path.join(log_map_dir, run_name)
            run_writer = SummaryWriter(log_dir=run_log_dir)

            print(f"\n Running Optuna Trial {trial.number} for {map_comb_name} with Seed: {current_run_seed} ")
            print(f"\n Trial Hyperparameters: {trial.params}")

            # Initialize the base environment
            base_env = MultiAgentMonitoring(
                map_size=map_config["map_size"],
                num_agents=map_config["num_agents"],
                movement_cost_factor=trial_args.movement_cost_factor,
                sensor_stds=map_config["sensor_stds"],
                max_episode_steps=trial_args.max_episode_steps,
                map_data_path=map_data_path,
                reward_scale_factor=trial_args.reward_scale_factor,
                collision_threshold=trial_args.collision_threshold,
                collision_penalty=trial_args.collision_penalty,
                reward_visited_cells=trial_args.reward_visited_cells,
                reward_peak_discovery=trial_args.reward_peak_discovery,
                penalty_time=trial_args.penalty_time, # Tuned
                penalty_revisit=trial_args.penalty_revisit # Using base arg, not tuning
            )
            # Wrap the base environment with the StateNormalizer
            env = StateNormalizer(base_env)

            observation_dim = env.observation_space.shape[0]
            action_dim = env.action_space.shape[0] * env.action_space.shape[1]

            print(f"Environment map size set to {env.env.map_size} from loaded file.")
            print(f"Environment initialized successfully.")
            print(f"Observation Dimension: {observation_dim}")
            print(f"Action Dimension: {action_dim}")

            # Initialize SACAgent with trial-specific args (which now include tuned lr, gamma, batch_size)
            agent = SACAgent(observation_dim, action_dim, trial_args, run_writer)
            replay_buffer = agent.replay_buffer # Assuming SACAgent constructor handles replay_buffer setup

            print(f"TensorBoard logs for trial saved to: {run_log_dir}")
            print("\n Starting Training for Trial")

            total_num_steps = 0
            training_episode_count = 0

            # Initial reset of the wrapped environment
            obs, info = env.reset(seed=current_run_seed + training_episode_count)
            episode_reward = 0
            episode_steps = 0
            done = False
            truncated = False

            while total_num_steps < trial_args.num_steps:
                while not done and not truncated:
                    if trial_args.start_steps > total_num_steps:
                        random_action = env.action_space.sample()
                        action = random_action.flatten()
                        action_reshaped_for_env = random_action
                    else:
                        if total_num_steps == trial_args.start_steps:
                           print("\n Random exploration complete. Freezing state normalizer statistics.")
                           env.set_training_mode(False)
                        action = agent.select_action(obs)
                        action_reshaped_for_env = action.reshape(map_config["num_agents"], 2)

                    next_obs, reward, done, truncated, info = env.step(action_reshaped_for_env)
                    replay_buffer.push(obs, action, reward, next_obs, done)

                    obs = next_obs
                    episode_reward += reward
                    episode_steps += 1
                    total_num_steps += 1

                    if len(replay_buffer) > trial_args.batch_size:
                        if total_num_steps >= trial_args.start_steps:
                            agent.update_parameters(replay_buffer, trial_args.batch_size, agent.updates, run_writer)
                            agent.updates += 1

                training_episode_count += 1
                run_writer.add_scalar('episode/reward', episode_reward, training_episode_count)
                run_writer.add_scalar('episode/steps', episode_steps, training_episode_count)
                print(f"\n Trial {trial.number}, Episode: {training_episode_count}, Steps: {total_num_steps}, Reward: {episode_reward:.4f}")

                # Evaluate and report metrics to Optuna periodically, especially for pruning
                if training_episode_count % trial_args.eval_interval == 0 and total_num_steps >= trial_args.start_steps:
                    eval_metrics_periodic = evaluate_agent(env, agent, trial_args.num_eval_episodes, current_run_seed, run_log_dir, f"{run_name}_periodic_eval_{training_episode_count}")
                    trial.report(eval_metrics_periodic["Avg. Reward"], training_episode_count)

                    if trial.should_prune():
                        print(f"Trial {trial.number} pruned at episode {training_episode_count}.")
                        env.close()
                        run_writer.close()
                        raise optuna.exceptions.TrialPruned()

                # Reset environment for the next episode
                obs, info = env.reset(seed=current_run_seed + training_episode_count)
                episode_reward = 0
                episode_steps = 0
                done = False
                truncated = False

            print("\n Training Complete for Trial")

            # Evaluate after training
            eval_metrics = evaluate_agent(env, agent, trial_args.num_eval_episodes, current_run_seed, run_log_dir, run_name)

            run_writer.close()
            env.close()

            # Store results for this trial for later saving/analysis
            trial_results = {
                "trial_number": trial.number,
                "hyperparameters": trial.params,
                "metrics": {k: float(v) if isinstance(v, (np.float32, np.float64)) else v for k, v in eval_metrics.items()},
                "log_dir": run_log_dir
            }
            all_trials_results_map.append(trial_results)

            # Optuna's objective: return the metric to maximize
            return eval_metrics["Avg. Reward"]

        # Optuna Study Setup and Optimization for the current map
        study = optuna.create_study(direction="maximize",
                                     sampler=optuna.samplers.TPESampler(seed=args.seed),
                                     pruner=optuna.pruners.MedianPruner(
                                         n_startup_trials=args.pruner_startup_trials,
                                         n_warmup_steps=args.pruner_warmup_episodes,
                                         interval_steps=args.eval_interval
                                     ))

        study.optimize(objective, n_trials=args.num_trials, timeout=args.tuning_timeout)

        print(f"\n Optuna Study Complete for {map_comb_name} ")
        print("\n Number of finished trials: ", len(study.trials))
        print("\n Best trial:")
        best_trial = study.best_trial
        print(f"  Value (Avg. Reward): {best_trial.value:.4f}")
        print("  Params: ")
        for key, value in best_trial.params.items():
            print(f"    {key}: {value}")

        # Find the full evaluation metrics for the best trial
        best_trial_metrics = None
        for trial_result in all_trials_results_map:
            if trial_result["trial_number"] == best_trial.number:
                best_trial_metrics = trial_result["metrics"]
                break

        # Save best trial information for this map, including all evaluation metrics
        best_trial_info_map = {
            "map_name": map_comb_name,
            "best_value_avg_reward": best_trial.value,
            "best_hyperparameters": best_trial.params,
            "best_trial_metrics": best_trial_metrics, # Include all metrics here
            "datetime_finished": datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        }
        best_trial_path_map = os.path.join(log_map_dir, "best_trial_summary.json")
        with open(best_trial_path_map, 'w') as f:
            json.dump(best_trial_info_map, f, indent=4)
        print(f"Best trial summary for {map_comb_name} saved to {best_trial_path_map}")

        # Save all trial results for this map
        all_trials_path_map = os.path.join(log_map_dir, "all_trials_results.json")
        with open(all_trials_path_map, 'w') as f:
            json.dump(all_trials_results_map, f, indent=4)
        print(f"\n All trials results for {map_comb_name} saved to {all_trials_path_map}")

        # Store the best result for this map in the overall summary, including all metrics
        results_summary_overall[map_comb_name] = {
            "Avg Reward": f"{best_trial.value:.4f}",
            "Best Hyperparameters": best_trial.params,
            "Evaluation Metrics": best_trial_metrics # Include all metrics in the overall summary
        }

    print("\nOverall Hyperparameter Tuning Complete")
    print("\nSummary of Best Found Configurations per Map:")
    # Save overall summary
    overall_summary_path = os.path.join(log_base_dir_overall, "overall_tuning_summary.json")
    with open(overall_summary_path, 'w') as f:
        json.dump(results_summary_overall, f, indent=4)
    print(f"\n Overall tuning summary saved to {overall_summary_path}")

    # Print overall summary to console
    for map_name, metrics_and_params in results_summary_overall.items():
        print(f"\n {map_name} ")
        print(f"\n Avg Reward: {metrics_and_params['Avg Reward']}")
        print("\n Best Hyperparameters:")
        for key, value in metrics_and_params['Best Hyperparameters'].items():
            print(f"  {key}: {value}")
        print("\n Evaluation Metrics:")
        for metric_name, value in metrics_and_params['Evaluation Metrics'].items():
              print(f"  {metric_name}: {value}")

# Main Execution Loop
if __name__ == '__main__':
    import argparse
    import torch
    import os
    import numpy as np
    from datetime import datetime
    from torch.utils.tensorboard import SummaryWriter
    import random

    parser = argparse.ArgumentParser(description="Multi-Agent Monitoring SAC Hyperparameter Tuning")

    parser.add_argument('--gamma', type=float, default=0.99, help='discount factor for reward (default: 0.99)')
    parser.add_argument('--tau', type=float, default=0.005, help='target smoothing coefficient(τ) (default: 0.005)')
    parser.add_argument('--lr', type=float, default=0.0003, help='learning rate (default: 0.0003)')
    parser.add_argument('--alpha', type=float, default=0.2, help='Temperature parameter α (default: 0.2)')
    parser.add_argument('--auto_entropy_tuning', type=bool, default=True, help='Autonomously adjust α (default: True)')
    parser.add_argument('--hidden_size', type=int, default=256, help='hidden size for neural networks (default: 256)')
    parser.add_argument('--replay_size', type=int, default=1000000, help='size of replay buffer (default: 1000000)')
    parser.add_argument('--batch_size', type=int, default=512, help='batch size for training (default: 256)')
    parser.add_argument('--num_steps', type=int, default=100000, help='maximum number of training steps PER TRIAL')
    parser.add_argument('--start_steps', type=int, default=50000, help='Steps for random action exploration (default: 1000)')

    parser.add_argument('--movement_cost_factor', type=float, default=0.005, help='Cost factor for agent movement (default: 0.005)')
    parser.add_argument('--max_episode_steps', type=int, default=1000, help='Maximum steps per episode (default: 1000)')
    parser.add_argument('--reward_scale_factor', type=float, default=1.0, help='Factor to scale the total reward by (default: 1.0)')

    parser.add_argument('--collision_threshold', type=float, default=0.05,
                         help='Normalized GT map value below which a cell is considered an obstacle (default: 0.05)')
    parser.add_argument('--collision_penalty', type=float, default=-2.0, # This will be a base value, tuned by Optuna
                         help='Reward penalty for colliding with an obstacle or map boundary (default: -2.0)')

    parser.add_argument('--reward_visited_cells', type=float, default=2.0, help='Weight for visiting new cells (default: 2.0)') # Base value, tuned by Optuna
    parser.add_argument('--reward_peak_discovery', type=float, default=10.0, help='Weight for discovering high peaks (default: 10.0)') # Base value, tuned by Optuna
    parser.add_argument('--penalty_time', type=float, default=0.00001, help='Penalty per time step (default: 0.00001)') # Base value, tuned by Optuna
    parser.add_argument('--penalty_revisit', type=float, default=0.0, help='Penalty for revisiting cells (default: 0.0)') # Not tuned in this example

    parser.add_argument('--num_eval_episodes', type=int, default=5, help='Number of episodes for evaluation after training (default: 5)')
    parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducibility (default: 42)')

    parser.add_argument('--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu', help='Device to run on (cpu or cuda)')

    # Optuna Specific Arguments
    parser.add_argument('--num_trials', type=int, default=3, help='Number of different hyperparameter combinations to try (default: 10)')
    parser.add_argument('--tuning_timeout', type=int, default=None, help='Total time limit for the tuning in seconds (e.g., 3600 for 1 hour), None for no limit (default: None)')
    parser.add_argument('--eval_interval', type=int, default=100, help='Evaluate and report to Optuna every X training episodes for pruning (default: 100)') # Evaluate every 100 episodes for pruning
    parser.add_argument('--pruner_startup_trials', type=int, default=5, help='Number of trials before pruning starts (default: 5)')
    parser.add_argument('--pruner_warmup_episodes', type=int, default=500, help='Number of episodes within a trial before pruning starts (default: 500)') # Warmup for pruning

    args, unknown = parser.parse_known_args()

    print(f"Using device: {args.device}")

    full_map_configs = {
        "Comb.1_Ypacarai_Large": {
            "map_data_path": "Environment/Maps/ypacarai_lake_58x41.csv",
            "num_agents": 2,
            "sensor_stds": 0.05,
            "map_size": (58, 41)
        },
        "Comb.2_Acoruna_Port": {
            "map_data_path": "Environment/Maps/acoruna_port.csv",
            "num_agents": 2,
            "sensor_stds": 0.05,
            "map_size": (62, 46)
        },
        "Comb.3_Ypacarai_Full": {
            "map_data_path": "Environment/Maps/ypacarai_map.csv",
            "num_agents": 2,
            "sensor_stds": 0.05,
            "map_size": (150, 121)
        },
        "Comb.4_Ypacarai_LowRes": {
            "map_data_path": "Environment/Maps/ypacarai_map_low_res.csv",
            "num_agents": 2,
            "sensor_stds": 0.05,
            "map_size": (58, 38)
        }
    }

    dummy_map_dir = "Environment/Maps"
    os.makedirs(dummy_map_dir, exist_ok=True)

    for map_name, map_config in full_map_configs.items():
        map_path = map_config["map_data_path"]
        if not os.path.exists(map_path):
            print(f"Map file not found: {map_path}. Creating a dummy map for testing.")
            rows, cols = map_config["map_size"]
            dummy_map_data = np.random.rand(rows, cols)
            dummy_map_data[rows//4:rows//2, cols//4:cols//2] = np.random.uniform(0, 0.04, size=(rows//4, cols//4))
            try:
                np.savetxt(map_path, dummy_map_data, delimiter=',')
                print(f"Created dummy map file: {map_path} (CSV with comma delimiter).")
            except Exception as e_comma:
                 print(f"Could not save dummy map as comma-delimited CSV: {e_comma}. Trying with space delimiter.")
                 try:
                     np.savetxt(map_path, dummy_map_data, delimiter=' ')
                     print(f"Created dummy map file: {map_path} (CSV with space delimiter).")
                 except Exception as e_space:
                     print(f"Could not save dummy map with space delimiter either: {e_space}. Please ensure map files exist.")

    # Pass the full_map_configs to the training function
    run_training_and_evaluation(args, full_map_configs)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs_tuning