# -*- coding: utf-8 -*-
"""Path Planning[Ground Truth] .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jT1hboCgIEzDi8J7pJlCc5ak18frCoeJ
"""

# Install libraries
!pip install -q gpytorch tabulate tqdm easydict
!pip install gymnasium
!pip install tensorboard
!pip install --upgrade sympy

# Create project directories
!mkdir -p Environment/GroundTruth
!mkdir -p Algorithm/DRL/Agent/SAC

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Normal
from collections import deque
import random
import os
import csv
import matplotlib.pyplot as plt
from scipy.interpolate import LinearNDInterpolator
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from torch.utils.tensorboard import SummaryWriter
from datetime import datetime
import argparse
import sys
import json
import warnings

#Environment & Ground truth definitions
class AlgaeBloomGroundTruth:
    @staticmethod
    def generate_map(map_size, map_seed=None):
        if map_seed is not None:
            np.random.seed(map_seed)

        data = np.zeros(map_size)
        num_blooms = np.random.randint(2, 5) # Create 2 to 4 blooms

        for _ in range(num_blooms):
            center_x = np.random.uniform(0.1, 0.9) * map_size[1]
            center_y = np.random.uniform(0.1, 0.9) * map_size[0]
            radius_x = np.random.uniform(0.1, 0.3) * map_size[1]
            radius_y = np.random.uniform(0.1, 0.3) * map_size[0]
            amplitude = np.random.uniform(0.5, 1.0)
            X, Y = np.meshgrid(np.arange(map_size[1]), np.arange(map_size[0]))
            data += amplitude * np.exp(-((X - center_x)**2 / (2 * radius_x**2) + (Y - center_y)**2 / (2 * radius_y**2)))

        # Normalize the final map
        if np.max(data) > np.min(data):
            data = (data - data.min()) / (data.max() - data.min())
        else:
            data = np.zeros(map_size)
        return data

class ShekelGroundTruth:
    @staticmethod
    def generate_map(map_size, map_seed=None):
        if map_seed is not None:
            np.random.seed(map_seed)

        num_peaks = np.random.randint(5, 12)
        peaks_A = np.random.rand(num_peaks) * 10
        peaks_C = np.random.rand(num_peaks, 2)
        peaks_C[:, 0] *= map_size[1]
        peaks_C[:, 1] *= map_size[0]

        X, Y = np.meshgrid(np.arange(map_size[1]), np.arange(map_size[0]))
        data = np.zeros(map_size)

        for i in range(num_peaks):
            # Using Shekel function structure
            denominator = ((X - peaks_C[i, 0])**2 + (Y - peaks_C[i, 1])**2) + peaks_A[i]
            data += 1 / (denominator + 1e-6)

        # Normalize the final map
        if np.max(data) > np.min(data):
            data = (data - data.min()) / (data.max() - data.min())
        else:
            data = np.zeros(map_size)
        return data

class MultiAgentMonitoring(gym.Env):
    def __init__(self, map_size, num_agents, movement_cost_factor, sensor_stds, max_episode_steps,
                 map_class=None, map_seed=None,
                 reward_scale_factor=1.0, collision_threshold=0.05,
                 # Reward weights passed as args
                 collision_penalty=-5.0, reward_visited_cells=1.0,
                 reward_peak_discovery=5.0, penalty_time=0.00001, penalty_revisit=0.0):
        super(MultiAgentMonitoring, self).__init__()

        self.map_size = map_size
        self.num_agents = num_agents
        self.movement_cost_factor = movement_cost_factor
        self.sensor_stds = sensor_stds
        self.max_episode_steps = max_episode_steps
        self.reward_scale_factor = reward_scale_factor
        self.collision_threshold = collision_threshold
        self.collision_penalty = collision_penalty

        self.map_class = map_class
        self.map_seed = map_seed
        self.gt_map = None
        self.gt_map_normalized = None

        self.reward_weights = {
            'visited_cells': reward_visited_cells,
            'peak_discovery': reward_peak_discovery,
            'time_penalty': penalty_time,
            'revisit_penalty': penalty_revisit
        }

        # Observation space to include sensed value
        self.observation_dim = self.num_agents * 3 # (x, y, value) for each agent
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(self.observation_dim,), dtype=np.float32)

        # Action space: num_agents * 2 (for x, y delta)
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(self.num_agents, 2), dtype=np.float32)

        self.current_step = 0
        self.fleet_positions = None
        self.visited_map = np.zeros(self.map_size)
        self.initial_visited_cells_count = 0
        self.np_random = None

    def _generate_new_map(self):
        if self.map_class:
            # Use a new seed for each map generation to ensure variety
            current_seed = self.np_random.integers(0, 2**32 - 1)
            self.gt_map = self.map_class.generate_map(self.map_size, map_seed=current_seed)
            self.gt_map_normalized = self.gt_map
        else:
            # Fallback to a random map if no class is provided
            self.gt_map = self.np_random.random(self.map_size)
            self.gt_map_normalized = self.gt_map

    def _get_obs(self):
        obs = []
        for i in range(self.num_agents):
            x, y = self.fleet_positions[i]
            # Discretize position to read from the map grid
            x_int, y_int = int(round(x)), int(round(y))
            x_int = np.clip(x_int, 0, self.map_size[1] - 1)
            y_int = np.clip(y_int, 0, self.map_size[0] - 1)
            true_value = self.gt_map_normalized[y_int, x_int]

            noisy_value = true_value + self.np_random.normal(0, self.sensor_stds)
            noisy_value = np.clip(noisy_value, 0.0, 1.0)
            # Normalize positions to [0, 1] range for the observation
            obs.extend([x / (self.map_size[1] - 1), y / (self.map_size[0] - 1), noisy_value])
        return np.array(obs, dtype=np.float32)

    def _sense_and_record(self):
        sensed_values_at_step = []
        for i in range(self.num_agents):
            x, y = self.fleet_positions[i]
            x_int, y_int = int(round(x)), int(round(y))
            x_int = np.clip(x_int, 0, self.map_size[1] - 1)
            y_int = np.clip(y_int, 0, self.map_size[0] - 1)
            true_value = self.gt_map_normalized[y_int, x_int]
            noisy_value = true_value + self.np_random.normal(0, self.sensor_stds)
            noisy_value = np.clip(noisy_value, 0.0, 1.0)
            sensed_values_at_step.append((x, y, noisy_value))
            # Mark cell as visited if it's not an obstacle
            if true_value >= self.collision_threshold:
                self.visited_map[y_int, x_int] = 1
        return sensed_values_at_step

    def _calculate_reward(self, current_sensed_values_info):
        reward = 0.0
        # Reward for visiting NEW cells
        current_visited_cells_count = np.sum(self.visited_map)
        newly_visited_cells = current_visited_cells_count - self.initial_visited_cells_count
        reward += self.reward_weights['visited_cells'] * newly_visited_cells
        self.initial_visited_cells_count = current_visited_cells_count

        # Reward for discovering high-value peaks, based on sensed value
        current_step_sensed_values = [val for _, _, val in current_sensed_values_info]
        if current_step_sensed_values:
            peak_reward = np.max(current_step_sensed_values)
            reward += self.reward_weights['peak_discovery'] * peak_reward

        # Penalty for time
        reward -= self.reward_weights['time_penalty']
        return reward

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        if seed is not None:
            self.np_random, _ = gym.utils.seeding.np_random(seed)
        else:
            self.np_random, _ = gym.utils.seeding.np_random()

        self._generate_new_map()

        self.fleet_positions = np.zeros((self.num_agents, 2), dtype=np.float32)
        # Initialize agents in valid non-obstacle positions
        for i in range(self.num_agents):
            valid_pos_found = False
            attempts = 0
            while not valid_pos_found and attempts < 1000:
                x = self.np_random.uniform(0, self.map_size[1])
                y = self.np_random.uniform(0, self.map_size[0])
                x_int, y_int = int(round(x)), int(round(y))
                if 0 <= y_int < self.map_size[0] and 0 <= x_int < self.map_size[1]:
                    if self.gt_map_normalized[y_int, x_int] >= self.collision_threshold:
                        self.fleet_positions[i, 0] = x
                        self.fleet_positions[i, 1] = y
                        valid_pos_found = True
                attempts += 1
            if not valid_pos_found:
                print(f"Warning: Could not find a valid start pos for agent {i}. Placing at (0,0).")
                self.fleet_positions[i, 0] = 0
                self.fleet_positions[i, 1] = 0

        self.current_step = 0
        self.visited_map = np.zeros(self.map_size)
        self.initial_visited_cells_count = 0
        initial_sensed_values = self._sense_and_record()
        self.initial_visited_cells_count = np.sum(self.visited_map)

        obs = self._get_obs()
        info = {"fleet_positions": self.fleet_positions.copy(), "sensed_values": initial_sensed_values}
        return obs, info

    def step(self, action):
        action = np.array(action).reshape(self.num_agents, 2)
        old_positions = self.fleet_positions.copy()
        collision_reward_penalty = 0.0

        intended_new_positions = self.fleet_positions + action
        new_fleet_positions = old_positions.copy()

        for i in range(self.num_agents):
            int_x = int(round(intended_new_positions[i, 0]))
            int_y = int(round(intended_new_positions[i, 1]))

            if 0 <= int_x < self.map_size[1] and 0 <= int_y < self.map_size[0]:
                if self.gt_map_normalized[int_y, int_x] < self.collision_threshold:
                    collision_reward_penalty += self.collision_penalty
                else:
                    new_fleet_positions[i] = intended_new_positions[i]
            else:
                new_fleet_positions[i, 0] = np.clip(intended_new_positions[i, 0], 0, self.map_size[1] - 1)
                new_fleet_positions[i, 1] = np.clip(intended_new_positions[i, 1], 0, self.map_size[0] - 1)
                collision_reward_penalty += self.collision_penalty

        self.fleet_positions = new_fleet_positions
        movement_cost = np.sum(np.abs(action)) * self.movement_cost_factor

        current_sensed_values_info = self._sense_and_record()
        reward_from_env = self._calculate_reward(current_sensed_values_info)

        # Combine all reward components and apply scale factor
        reward = (reward_from_env - movement_cost + collision_reward_penalty) * self.reward_scale_factor

        self.current_step += 1
        terminated = False
        truncated = self.current_step >= self.max_episode_steps

        obs = self._get_obs()
        info = {"fleet_positions": self.fleet_positions.copy(), "sensed_values": current_sensed_values_info}
        return obs, reward, terminated, truncated, info

    def render(self):
        plt.figure(figsize=(10, 8))
        if self.gt_map_normalized is not None:
            plt.imshow(self.gt_map_normalized, origin='lower', cmap='viridis', alpha=0.7)
            obstacle_mask = self.gt_map_normalized < self.collision_threshold
            plt.imshow(obstacle_mask, origin='lower', cmap='binary', alpha=0.5)
        plt.imshow(self.visited_map, origin='lower', cmap='bone_r', alpha=0.3)
        if self.fleet_positions is not None:
            plt.scatter(self.fleet_positions[:, 0], self.fleet_positions[:, 1], c='red', marker='o', s=100, label='Agents', edgecolors='black')
        plt.title(f"Map Monitoring - Step: {self.current_step}")
        plt.xlabel("X Coordinate")
        plt.ylabel("Y Coordinate")
        plt.colorbar(label="Normalized Value")
        plt.legend()
        plt.grid(True)
        plt.show()

    def close(self):
        plt.close()

#State Normalizer & Replay Buffer
class StateNormalizer(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)
        self.state_sum = np.zeros(self.observation_space.shape, dtype=np.float32)
        self.state_sq_sum = np.zeros(self.observation_space.shape, dtype=np.float32)
        self.state_count = 0
        self.state_mean = np.zeros(self.observation_space.shape, dtype=np.float32)
        self.state_std = np.ones(self.observation_space.shape, dtype=np.float32)
        self.epsilon = 1e-8
        self.is_training = True

    def _update_stats(self, obs):
        if not self.is_training:
            return
        self.state_sum += obs
        self.state_sq_sum += obs ** 2
        self.state_count += 1
        self.state_mean = self.state_sum / self.state_count
        self.state_std = np.sqrt(np.maximum(self.state_sq_sum / self.state_count - self.state_mean ** 2, self.epsilon))

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        self._update_stats(obs)
        normalized_obs = (obs - self.state_mean) / self.state_std
        return normalized_obs, info

    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)
        self._update_stats(obs)
        normalized_obs = (obs - self.state_mean) / self.state_std
        return normalized_obs, reward, terminated, truncated, info

    def set_training_mode(self, mode):
        self.is_training = mode

class ReplayBuffer:
    def __init__(self, capacity):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size):
        if len(self.buffer) < batch_size:
            raise ValueError(f"Replay buffer needs at least {batch_size} samples, but has only {len(self.buffer)}.")
        state, action, reward, next_state, done = zip(*random.sample(self.buffer, batch_size))
        return np.array(state, dtype=np.float32), np.array(action, dtype=np.float32), \
               np.array(reward, dtype=np.float32), np.array(next_state, dtype=np.float32), \
               np.array(done, dtype=np.float32)

    def __len__(self):
        return len(self.buffer)

# Netwroks for SAC
class ValueNetwork(nn.Module):
    def __init__(self, observation_dim, hidden_size):
        super(ValueNetwork, self).__init__()
        self.fc1 = nn.Linear(observation_dim, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, 1)
    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

class QNetwork(nn.Module):
    def __init__(self, observation_dim, action_dim, hidden_size):
        super(QNetwork, self).__init__()
        # Q1
        self.fc1_q1 = nn.Linear(observation_dim + action_dim, hidden_size)
        self.fc2_q1 = nn.Linear(hidden_size, hidden_size)
        self.fc3_q1 = nn.Linear(hidden_size, 1)
        # Q2
        self.fc1_q2 = nn.Linear(observation_dim + action_dim, hidden_size)
        self.fc2_q2 = nn.Linear(hidden_size, hidden_size)
        self.fc3_q2 = nn.Linear(hidden_size, 1)
    def forward(self, state, action):
        sa = torch.cat([state, action], 1)
        x1 = F.relu(self.fc1_q1(sa))
        x1 = F.relu(self.fc2_q1(x1))
        q1 = self.fc3_q1(x1)
        x2 = F.relu(self.fc1_q2(sa))
        x2 = F.relu(self.fc2_q2(x2))
        q2 = self.fc3_q2(x2)
        return q1, q2

class GaussianPolicy(nn.Module):
    def __init__(self, observation_dim, action_dim, hidden_size):
        super(GaussianPolicy, self).__init__()
        self.fc1 = nn.Linear(observation_dim, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.mean_linear = nn.Linear(hidden_size, action_dim)
        self.log_std_linear = nn.Linear(hidden_size, action_dim)
        self.log_std_min = -20
        self.log_std_max = 2
    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        mean = self.mean_linear(x)
        log_std = self.log_std_linear(x)
        log_std = torch.clamp(log_std, self.log_std_min, self.log_std_max)
        return mean, log_std
    def sample(self, state):
        mean, log_std = self.forward(state)
        std = log_std.exp()
        normal = Normal(mean, std)
        z = normal.rsample() # Use rsample for reparameterization trick
        action = torch.tanh(z)
        log_prob = normal.log_prob(z) - torch.log(1 - action.pow(2) + 1e-6)
        log_prob = log_prob.sum(1, keepdim=True)
        return action, log_prob, mean, log_std

#SAC Agent
class SACAgent:
    def __init__(self, observation_dim, action_dim, args, writer):
        self.gamma = args.gamma
        self.tau = args.tau
        self.lr = args.lr
        self.alpha = torch.tensor(args.alpha, requires_grad=False, device=args.device)
        self.auto_entropy_tuning = args.auto_entropy_tuning
        self.target_entropy = -torch.prod(torch.Tensor([action_dim]).to(args.device)).item()
        self.hidden_size = args.hidden_size
        self.device = args.device
        self.writer = writer

        self.value_net = ValueNetwork(observation_dim, self.hidden_size).to(self.device)
        self.target_value_net = ValueNetwork(observation_dim, self.hidden_size).to(self.device)
        self.q_net1 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)
        self.q_net2 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)
        self.policy_net = GaussianPolicy(observation_dim, action_dim, self.hidden_size).to(self.device)

        # Use a single Q-network class with two instances for soft updates
        self.target_q_net1 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)
        self.target_q_net2 = QNetwork(observation_dim, action_dim, self.hidden_size).to(self.device)

        # Copy weights
        self.target_value_net.load_state_dict(self.value_net.state_dict())
        self.target_q_net1.load_state_dict(self.q_net1.state_dict())
        self.target_q_net2.load_state_dict(self.q_net2.state_dict())

        self.value_optimizer = optim.Adam(self.value_net.parameters(), lr=self.lr)
        # Combine Q-network parameters for a single optimizer
        self.q_optimizer = optim.Adam(list(self.q_net1.parameters()) + list(self.q_net2.parameters()), lr=self.lr)
        self.policy_optimizer = optim.Adam(self.policy_net.parameters(), lr=self.lr)

        if self.auto_entropy_tuning:
            self.log_alpha = torch.tensor(np.log(self.alpha.item()), requires_grad=True, device=self.device)
            self.alpha_optimizer = optim.Adam([self.log_alpha], lr=self.lr)

        self.replay_buffer = ReplayBuffer(args.replay_size)
        self.updates = 0

    def select_action(self, state, evaluate=False):
        state = torch.FloatTensor(state).to(self.device).unsqueeze(0)
        if not evaluate:
            action, _, _, _ = self.policy_net.sample(state)
        else:
            mean, _ = self.policy_net.forward(state)
            action = torch.tanh(mean)
        return action.detach().cpu().numpy()[0]

    def update_parameters(self, memory, batch_size, updates, writer):
        try:
            state_batch, action_batch, reward_batch, next_state_batch, terminated_batch = memory.sample(batch_size)
        except ValueError as e:
            print(f"Warning: {e}")
            return

        state_batch = torch.FloatTensor(state_batch).to(self.device)
        next_state_batch = torch.FloatTensor(next_state_batch).to(self.device)
        action_batch = torch.FloatTensor(action_batch).to(self.device)
        reward_batch = torch.FloatTensor(reward_batch).unsqueeze(1).to(self.device)
        terminated_batch = torch.FloatTensor(terminated_batch).unsqueeze(1).to(self.device)

        with torch.no_grad():
            next_state_action, next_state_log_pi, _, _ = self.policy_net.sample(next_state_batch)
            q1_next_target, q2_next_target = self.target_q_net1(next_state_batch, next_state_action)
            min_q_next_target = torch.min(q1_next_target, q2_next_target) - self.alpha * next_state_log_pi
            next_q_value = reward_batch + (1 - terminated_batch) * self.gamma * min_q_next_target

        q1, q2 = self.q_net1(state_batch, action_batch)
        q1_loss = F.mse_loss(q1, next_q_value)
        q2_loss = F.mse_loss(q2, next_q_value)
        q_loss = q1_loss + q2_loss

        self.q_optimizer.zero_grad()
        q_loss.backward()
        self.q_optimizer.step()

        pi, log_pi, _, _ = self.policy_net.sample(state_batch)
        q1_pi, q2_pi = self.q_net1(state_batch, pi)
        min_q_pi = torch.min(q1_pi, q2_pi)
        policy_loss = ((self.alpha * log_pi) - min_q_pi).mean()

        self.policy_optimizer.zero_grad()
        policy_loss.backward()
        self.policy_optimizer.step()

        alpha_loss = torch.tensor(0.0).to(self.device)
        if self.auto_entropy_tuning:
            alpha_loss = -(self.log_alpha * (log_pi + self.target_entropy).detach()).mean()
            self.alpha_optimizer.zero_grad()
            alpha_loss.backward()
            self.alpha_optimizer.step()
            self.alpha = self.log_alpha.exp()

        # Soft update target networks
        for target_param, param in zip(self.target_q_net1.parameters(), self.q_net1.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)
        for target_param, param in zip(self.target_q_net2.parameters(), self.q_net2.parameters()):
            target_param.data.copy_(target_param.data * (1.0 - self.tau) + param.data * self.tau)

        if writer is not None:
            writer.add_scalar('loss/q_loss', q_loss.item(), updates)
            writer.add_scalar('loss/policy_loss', policy_loss.item(), updates)
            writer.add_scalar('alpha', self.alpha.item(), updates)
            writer.add_scalar('loss/alpha_loss', alpha_loss.item(), updates)

#Evaluate agent
def evaluate_agent(env, agent, num_episodes, seed, writer, hparams):
    print("\n Starting Evaluation")
    all_rewards, all_maes, all_mses, all_r2s, all_csmes = [], [], [], [], []
    for i in range(num_episodes):
        obs, info = env.reset(seed=seed + i)
        episode_reward = 0
        done, truncated = False, False
        sensed_coords = []
        sensed_values = []
        episode_squared_errors = []

        while not done and not truncated:
            action = agent.select_action(obs, evaluate=True)
            action_reshaped = action.reshape(env.unwrapped.num_agents, 2)
            obs, reward, done, truncated, info = env.step(action_reshaped)
            episode_reward += reward

            valid_sensed_data = [item for item in info["sensed_values"] if hasattr(item, '__iter__') and len(item) >= 2]

            temp_coords = []
            temp_values = []
            current_step_squared_errors = []
            for item in valid_sensed_data:
                try:
                    x, y, sensed_value = item
                    temp_coords.append([x, y])
                    temp_values.append(sensed_value)

                    # Calculate squared error for CSME at visited cells
                    x_int, y_int = int(round(x)), int(round(y))
                    x_int = np.clip(x_int, 0, env.unwrapped.map_size[1] - 1)
                    y_int = np.clip(y_int, 0, env.unwrapped.map_size[0] - 1)
                    true_value = env.unwrapped.gt_map_normalized[y_int, x_int]
                    squared_error = (sensed_value - true_value)**2
                    current_step_squared_errors.append(squared_error)

                except IndexError:
                    print(f"Warning: Skipping malformed data point: {item}")
                    continue

            sensed_coords.extend(temp_coords)
            sensed_values.extend(temp_values)
            episode_squared_errors.extend(current_step_squared_errors) # Accumulate squared errors


        all_rewards.append(episode_reward)

        sensed_coords_np = np.array(sensed_coords)

        # Calculate CSME for the episode
        if episode_squared_errors:
             csme = np.mean(episode_squared_errors)
             all_csmes.append(csme)
        else:
             all_csmes.append(np.nan) # Append NaN if no cells were visited

        if len(sensed_coords_np) >= 3:
            gt_map = env.unwrapped.gt_map_normalized
            grid_x, grid_y = np.meshgrid(np.arange(env.unwrapped.map_size[1]), np.arange(env.unwrapped.map_size[0]))
            try:
                estimated_map = LinearNDInterpolator(sensed_coords_np, sensed_values)(grid_x, grid_y)
                estimated_map[np.isnan(estimated_map)] = np.mean(sensed_values) if sensed_values else 0.0
                all_maes.append(mean_absolute_error(gt_map, estimated_map))
                all_mses.append(mean_squared_error(gt_map, estimated_map))
                all_r2s.append(r2_score(gt_map.flatten(), estimated_map.flatten()))
            except ValueError as e:
                print(f"Interpolation failed for this episode: {e}")
                all_maes.append(np.nan)
                all_mses.append(np.nan)
                all_r2s.append(np.nan)
        else:
            print(f"Not enough unique points ({len(sensed_coords_np)}) for interpolation in this episode.")
            all_maes.append(np.nan)
            all_mses.append(np.nan)
            all_r2s.append(np.nan)

    results = {
        "Avg Reward": np.mean(all_rewards),
        "MAE (Full Map)": np.nanmean(all_maes),
        "MSE (Full Map)": np.nanmean(all_mses),
        "R2 (Full Map)": np.nanmean(all_r2s),
        "CSME (Visited Cells)": np.nanmean(all_csmes)
    }
    print("Final Evaluation Results:")
    for key, value in results.items(): print(f"  {key}: {value:.4f}")

    sanitized_hparams = {k: v for k, v in hparams.items() if isinstance(v, (str, int, float, bool))}
    writer.add_hparams(sanitized_hparams, results)

    return results

!pip install -q optuna

#Training and Evaluation
import optuna
def set_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

def run_training_and_evaluation(args, map_configs):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    log_base_dir_overall = os.path.join("runs_tuning_groundtruth", f"Tune_Overall_{timestamp}")
    os.makedirs(log_base_dir_overall, exist_ok=True)

    best_trials_per_map = {}

    for map_comb_name, map_config in map_configs.items():
        print(f"\n Starting Optuna Hyperparameter Tuning for Map Type: {map_comb_name} ")
        log_map_dir = os.path.join(log_base_dir_overall, map_comb_name)
        os.makedirs(log_map_dir, exist_ok=True)

        def objective(trial):
            trial_args = type('Args', (object,), args.__dict__.copy())
            trial_args.lr = trial.suggest_float('lr', 1e-5, 1e-3, log=True)
            trial_args.batch_size = trial.suggest_categorical('batch_size', [128, 256, 512])
            trial_args.gamma = trial.suggest_float('gamma', 0.95, 0.999)
            trial_args.reward_visited_cells = trial.suggest_float('reward_visited_cells', 0.5, 5.0)
            trial_args.reward_peak_discovery = trial.suggest_float('reward_peak_discovery', 2.0, 20.0)
            trial_args.penalty_time = trial.suggest_float('penalty_time', 1e-5, 1e-2, log=True)
            trial_args.collision_penalty = trial.suggest_float('collision_penalty', -10.0, -1.0)

            current_run_seed = trial_args.seed + trial.number
            set_seed(current_run_seed)
            run_name = f"Trial{trial.number}_{datetime.now().strftime('%H-%M-%S')}"
            run_log_dir = os.path.join(log_map_dir, run_name)

            run_writer = SummaryWriter(log_dir=run_log_dir)


            print(f"\n Running Trial {trial.number} for {map_comb_name} ")
            print(f"\n Hyperparameters: {trial.params}")

            # Create base env and wrap with StateNormalizer
            base_env = MultiAgentMonitoring(
                map_size=map_config["map_size"], num_agents=map_config["num_agents"],
                movement_cost_factor=trial_args.movement_cost_factor, sensor_stds=map_config["sensor_stds"],
                max_episode_steps=trial_args.max_episode_steps, map_class=map_config["map_class"],
                reward_scale_factor=trial_args.reward_scale_factor, collision_threshold=trial_args.collision_threshold,
                collision_penalty=trial_args.collision_penalty, reward_visited_cells=trial_args.reward_visited_cells,
                reward_peak_discovery=trial_args.reward_peak_discovery, penalty_time=trial_args.penalty_time,
                penalty_revisit=trial_args.penalty_revisit
            )
            env = StateNormalizer(base_env)

            observation_dim = env.observation_space.shape[0]
            action_dim = np.prod(env.action_space.shape)

            agent = SACAgent(observation_dim, action_dim, trial_args, run_writer) # Pass run_writer to SACAgent
            total_num_steps = 0
            training_episode_count = 0

            # Main training loop
            while total_num_steps < trial_args.num_steps:
                obs, info = env.reset(seed=current_run_seed + training_episode_count)
                done, truncated = False, False
                episode_reward, episode_steps = 0, 0

                while not done and not truncated:
                    if total_num_steps < trial_args.start_steps:
                        action = env.action_space.sample().flatten()
                        action_reshaped = action.reshape(env.unwrapped.num_agents, 2)
                    else:
                        if total_num_steps == trial_args.start_steps:
                            print("\n Random exploration complete. Freezing state normalizer.")
                            env.set_training_mode(False)
                        action = agent.select_action(obs)
                        action_reshaped = action.reshape(env.unwrapped.num_agents, 2)

                    next_obs, reward, done, truncated, info = env.step(action_reshaped)
                    agent.replay_buffer.push(obs, action, reward, next_obs, done)
                    obs = next_obs
                    episode_reward += reward
                    episode_steps += 1
                    total_num_steps += 1

                    if len(agent.replay_buffer) > trial_args.batch_size and total_num_steps > trial_args.start_steps:
                        agent.update_parameters(agent.replay_buffer, trial_args.batch_size, agent.updates, run_writer)
                        agent.updates += 1

                run_writer.add_scalar('episode/reward', episode_reward, training_episode_count)
                print(f"\n Trial {trial.number}, Episode: {training_episode_count}, Steps: {total_num_steps}, Reward: {episode_reward:.2f}")
                training_episode_count += 1

                # Optuna pruning
                if training_episode_count % trial_args.eval_interval == 0:
                    trial.report(episode_reward, training_episode_count)
                    if trial.should_prune():
                        run_writer.close() # Close writer before pruning
                        raise optuna.exceptions.TrialPruned()

            print("\n Training Complete for Trial ")
            # Pass run_writer and trial.params to evaluate_agent
            eval_metrics = evaluate_agent(env, agent, trial_args.num_eval_episodes, current_run_seed, run_writer, trial.params)
            run_writer.close()
            env.close()
            return eval_metrics["Avg Reward"]


        study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner())
        study.optimize(objective, n_trials=args.num_trials)

        print(f"\n Optuna Study Complete for {map_comb_name} ")
        best_trial = study.best_trial
        print(f"\n Best trial value: {best_trial.value:.4f}")
        print("\n Best hyperparameters:")
        for key, value in best_trial.params.items():
            print(f"    {key}: {value}")

        best_trials_per_map[map_comb_name] = best_trial

    # Find and print overall best results
    print("\n" + "="*50)
    print("\n Overall Best Results Across All Map Types ")
    print("="*50)

    overall_best_trial = None
    overall_best_map_name = None

    # Print best results for each map type
    print("\n" + "-"*20)
    print(" Best Results Per Map Type ")
    print("-"*20)
    for map_name, trial in best_trials_per_map.items():
        print(f"\n Map Type: {map_name}")
        print(f"\n Best Trial Value: {trial.value:.4f}")
        print("\n Best Hyperparameters:")
        for key, value in trial.params.items():
            print(f"    {key}: {value}")

        if overall_best_trial is None or trial.value > overall_best_trial.value:
            overall_best_trial = trial
            overall_best_map_name = map_name


# Main Execution Block
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Multi-Agent Monitoring SAC Hyperparameter Tunning with Ground Truth Maps")

    parser.add_argument('--gamma', type=float, default=0.99)
    parser.add_argument('--tau', type=float, default=0.005)
    parser.add_argument('--lr', type=float, default=0.0003)
    parser.add_argument('--alpha', type=float, default=0.2)
    parser.add_argument('--auto_entropy_tuning', type=bool, default=True)
    parser.add_argument('--hidden_size', type=int, default=256)
    parser.add_argument('--replay_size', type=int, default=1000000)
    parser.add_argument('--batch_size', type=int, default=256)
    parser.add_argument('--num_steps', type=int, default=100000)
    parser.add_argument('--start_steps', type=int, default=50000)
    parser.add_argument('--max_episode_steps', type=int, default=1000)
    parser.add_argument('--movement_cost_factor', type=float, default=0.01)
    parser.add_argument('--reward_scale_factor', type=float, default=1.0)
    parser.add_argument('--collision_threshold', type=float, default=0.05)
    parser.add_argument('--collision_penalty', type=float, default=-5.0)
    parser.add_argument('--reward_visited_cells', type=float, default=1.0)
    parser.add_argument('--reward_peak_discovery', type=float, default=5.0)
    parser.add_argument('--penalty_time', type=float, default=0.0001)
    parser.add_argument('--penalty_revisit', type=float, default=0.0)
    parser.add_argument('--num_eval_episodes', type=int, default=10)
    parser.add_argument('--seed', type=int, default=123)
    parser.add_argument('--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu')
    parser.add_argument('--num_trials', type=int, default=3)
    parser.add_argument('--eval_interval', type=int, default=10)

    args, unknown = parser.parse_known_args()
    print(f"Using device: {args.device}")

    full_map_configs = {
        "AlgaeBloom_50x50": {
            "map_class": AlgaeBloomGroundTruth,
            "map_size": (50, 50),
            "num_agents": 2,
            "sensor_stds": 0.05,
        },
        "Shekel_60x40": {
            "map_class": ShekelGroundTruth,
            "map_size": (60, 40),
            "num_agents": 3,
            "sensor_stds": 0.05,
        }
    }

    run_training_and_evaluation(args, full_map_configs)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs_tuning